# Generated by Django 4.0.3 on 2022-03-31 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_post_postimage_delete_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='heading',
        ),
    ]
